//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkupConverterTests {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Documents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Documents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkupConverterTests.Documents", typeof(Documents).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;{0}&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string FullHtml_Format {
            get {
                return ResourceManager.GetString("FullHtml_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-indent:0;margin:0px 0px 0px 0px;font-family:Verdana;font-size:16px;&quot;&gt;Paragraph 1&lt;/p&gt;&lt;p /&gt;&lt;p style=&quot;text-indent:0;margin:0px 0px 0px 0px;font-family:Verdana;font-size:16px;&quot;&gt;Paragraph 2&lt;/p&gt;&lt;p style=&quot;text-indent:-22;margin:0px 0px 0px 38px;font-family:Verdana;font-size:16px;&quot;&gt;Test &lt;span&gt;capacitor&lt;/span&gt; inductor&lt;/p&gt;&lt;p style=&quot;text-indent:-22;margin:0px 0px 0px 38px;font-family:Verdana;font-size:16px;&quot;&gt;Transistor &lt;span&gt;resistor&lt;/span&gt;&lt;/p&gt;&lt;p /&gt;.
        /// </summary>
        internal static string TestParagraph_Html {
            get {
                return ResourceManager.GetString("TestParagraph_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument PagePadding=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Paragraph TextIndent=&quot;0&quot; Margin=&quot;0,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Paragraph 1&lt;/Paragraph&gt;
        ///    &lt;Paragraph xml:space=&quot;preserve&quot; /&gt;
        ///    &lt;Paragraph TextIndent=&quot;0&quot; Margin=&quot;0,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Paragraph 2&lt;/Paragraph&gt;
        ///    &lt;Paragraph TextIndent=&quot;-22&quot; Margin=&quot;37.8,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Test &lt;Run&gt;ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestParagraph_Xaml {
            get {
                return ResourceManager.GetString("TestParagraph_Xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xml:space=&quot;preserve&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///  &lt;Paragraph TextIndent=&quot;0&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;0&quot;&gt;Paragraph 1&lt;/Paragraph&gt;
        ///  &lt;Paragraph /&gt;
        ///  &lt;Paragraph TextIndent=&quot;0&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;0&quot;&gt;Paragraph 2&lt;/Paragraph&gt;
        ///  &lt;Paragraph TextIndent=&quot;-22&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;38,0,0,0&quot;&gt;Test &lt;Run&gt;capacitor&lt;/Run&gt; inductor&lt;/Paragraph&gt;
        ///  &lt;Paragraph TextIndent=&quot;-22&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestParagraph_XamlFromHtml {
            get {
                return ResourceManager.GetString("TestParagraph_XamlFromHtml", resourceCulture);
            }
        }
    }
}
