//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkupConverterTests {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Documents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Documents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkupConverterTests.Documents", typeof(Documents).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;{0}&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string FullHtml_Format {
            get {
                return ResourceManager.GetString("FullHtml_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span style=&quot;font-style:italic;font-weight:bold;text-decoration:line-through underline;&quot;&gt;word1 &lt;/span&gt;word2&lt;/p&gt;.
        /// </summary>
        internal static string MultipleFontStyles_HtmlFromXaml {
            get {
                return ResourceManager.GetString("MultipleFontStyles_HtmlFromXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xml:space=&quot;preserve&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;&lt;Paragraph&gt;&lt;Run FontStyle=&quot;Italic&quot; FontWeight=&quot;Bold&quot; xml:space=&quot;preserve&quot;&gt;&lt;Run.TextDecorations&gt;&lt;TextDecoration Location=&quot;Strikethrough&quot; /&gt;&lt;TextDecoration Location=&quot;Underline&quot; /&gt;&lt;/Run.TextDecorations&gt;word1 &lt;/Run&gt;word2&lt;/Paragraph&gt;&lt;/FlowDocument&gt;.
        /// </summary>
        internal static string MultipleFontStyles_Xaml {
            get {
                return ResourceManager.GetString("MultipleFontStyles_Xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: Verdana; font-size: 18.7px;&quot;&gt;
        ///&lt;table style=&quot;border-collapse: collapse; width: 100px;&quot;&gt;
        ///&lt;colgroup&gt;
        ///&lt;col style=&quot;width: 150px;&quot; /&gt;
        ///&lt;col style=&quot;width: 200px;&quot; /&gt;
        ///&lt;col style=&quot;width: 250px;&quot; /&gt;
        ///&lt;/colgroup&gt;
        ///&lt;tbody&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;padding: 0px 8px 0px 8px; border: 1px solid #000000;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td style=&quot;padding: 0px 8px 0px 8px; border: 1px solid #000000;&quot;&gt;a&lt;/td&gt;
        ///&lt;td style=&quot;padding: 0px 8px 0px 8px; border: 1px solid #000000;&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;padding: 0px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_Html {
            get {
                return ResourceManager.GetString("Table_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body style=&quot;font-family:Verdana;font-size:18.7px;&quot;&gt;&lt;table style=&quot;border-collapse:collapse;&quot;&gt;&lt;colgroup&gt;&lt;col style=&quot;width:100px;&quot; /&gt;&lt;col style=&quot;width:200px;&quot; /&gt;&lt;/colgroup&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style=&quot;padding:0px 8px 0px 8px;border-width:1px 1px 1px 1px;border-color:#000000;border-style:solid;&quot;&gt;&lt;p style=&quot;margin:0px 0px 0px 0px;text-align:Left;font-family:Calibri;font-size:14.7px;&quot;&gt;&lt;span&gt;a&lt;/span&gt;&lt;/p&gt;&lt;/td&gt;&lt;td style=&quot;padding:0px 8px 0px 8px;border-width:1px 1px 1px 1px;border-color:#000000;border-style:solid;&quot;&gt;&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_HtmlFromXaml {
            get {
                return ResourceManager.GetString("Table_HtmlFromXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument FontFamily=&quot;Verdana&quot; FontSize=&quot;18.6666666666667&quot; PagePadding=&quot;4,4,4,4&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///    &lt;Table CellSpacing=&quot;0&quot;&gt;
        ///        &lt;Table.Columns&gt;
        ///            &lt;TableColumn Width=&quot;100&quot; /&gt;
        ///            &lt;TableColumn Width=&quot;200&quot; /&gt;
        ///        &lt;/Table.Columns&gt;
        ///        &lt;TableRowGroup&gt;
        ///            &lt;TableRow&gt;
        ///                &lt;TableCell Padding=&quot;7.2,0,7.2,0&quot; BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;#FF000000&quot;&gt;
        ///                    &lt;Paragraph Margin=&quot;0,0,0,0&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_Xaml {
            get {
                return ResourceManager.GetString("Table_Xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xml:space=&quot;preserve&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;18.6666666666667&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;&lt;Table CellSpacing=&quot;0&quot;&gt;&lt;Table.Columns&gt;&lt;TableColumn Width=&quot;25&quot; /&gt;&lt;TableColumn Width=&quot;33.3333333333333&quot; /&gt;&lt;TableColumn Width=&quot;41.6666666666667&quot; /&gt;&lt;/Table.Columns&gt;&lt;TableRowGroup&gt;&lt;TableRow&gt;&lt;TableCell BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;Black&quot;&gt;&lt;Paragraph&gt; &lt;/Paragraph&gt;&lt;/TableCell&gt;&lt;TableCell BorderThickness=&quot;1,1,1,1&quot; BorderBrush=&quot;Black&quot;&gt;&lt;Paragraph&gt;a&lt;/Paragraph&gt;&lt;/T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_XamlFromHtml {
            get {
                return ResourceManager.GetString("Table_XamlFromHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-indent:0;margin:0px 0px 0px 0px;font-family:Verdana;font-size:16px;&quot;&gt;Paragraph 1&lt;/p&gt;&lt;p /&gt;&lt;p style=&quot;text-indent:0;margin:0px 0px 0px 0px;font-family:Verdana;font-size:16px;&quot;&gt;Paragraph 2&lt;/p&gt;&lt;p style=&quot;text-indent:-22;margin:0px 0px 0px 38px;font-family:Verdana;font-size:16px;&quot;&gt;Test &lt;span&gt;capacitor&lt;/span&gt; inductor&lt;/p&gt;&lt;p style=&quot;text-indent:-22;margin:0px 0px 0px 38px;font-family:Verdana;font-size:16px;&quot;&gt;Transistor &lt;span&gt;resistor&lt;/span&gt;&lt;/p&gt;&lt;p /&gt;.
        /// </summary>
        internal static string TestParagraph_Html {
            get {
                return ResourceManager.GetString("TestParagraph_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument PagePadding=&quot;0,0,0,0&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Paragraph TextIndent=&quot;0&quot; Margin=&quot;0,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Paragraph 1&lt;/Paragraph&gt;
        ///    &lt;Paragraph xml:space=&quot;preserve&quot; /&gt;
        ///    &lt;Paragraph TextIndent=&quot;0&quot; Margin=&quot;0,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Paragraph 2&lt;/Paragraph&gt;
        ///    &lt;Paragraph TextIndent=&quot;-22&quot; Margin=&quot;37.8,0,0,0&quot; FontFamily=&quot;Verdana&quot; FontSize=&quot;16&quot;&gt;Test &lt;Run&gt;ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestParagraph_Xaml {
            get {
                return ResourceManager.GetString("TestParagraph_Xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xml:space=&quot;preserve&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;&lt;Paragraph TextIndent=&quot;0&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;0&quot;&gt;Paragraph 1&lt;/Paragraph&gt;&lt;Paragraph /&gt;&lt;Paragraph TextIndent=&quot;0&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;0&quot;&gt;Paragraph 2&lt;/Paragraph&gt;&lt;Paragraph TextIndent=&quot;-22&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;38,0,0,0&quot;&gt;Test &lt;Run&gt;capacitor&lt;/Run&gt; inductor&lt;/Paragraph&gt;&lt;Paragraph TextIndent=&quot;-22&quot; FontFamily=&quot;verdana&quot; FontSize=&quot;16&quot; Margin=&quot;38,0,0,0&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestParagraph_XamlFromHtml {
            get {
                return ResourceManager.GetString("TestParagraph_XamlFromHtml", resourceCulture);
            }
        }
    }
}
